#!/usr/bin/env python3

"""
pyobf - python obfuscator
Copyright (C) 2026 benja2998
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import sys
import base64
import re
import argparse as ap
import random
import string

def test():
    no = "op"

def getfunc(line):
    function = re.search(r"^def .*\(.*\):", line)

    if function:
        functionname = re.split(r'def |\(', function.group())
        return functionname[1]
    else:
        return None

def getvar(line):
    variable = re.search(r"\w+ = ", line)

    if variable:
        variablename = re.split(r' = ', variable.group())
        return variablename[0]
    else:
        return None

def main():
    parser = ap.ArgumentParser()

    parser.add_argument('-i', '--input', required=True)
    parser.add_argument('-o', '--output', required=True)
    args = parser.parse_args()

    print(f"INPUT: {args.input}, OUTPUT: {args.output}")

    functionstoreplace = {}
    vartionstoreplace = {}

    with open(args.input, 'r', encoding="utf-8") as file:
        for line in file:
            thefunction = getfunc(line)

            if thefunction:
                length = 8
                newfunc = ''.join(
                    random.choices(
                        string.ascii_letters, k=length)).strip()
                functionstoreplace[thefunction.strip()] = newfunc

            thevartion = getvar(line)

            if thevartion:
                length = 8
                newvar = ''.join(
                    random.choices(
                        string.ascii_letters, k=length)).strip()
                vartionstoreplace[thevartion.strip()] = newvar

    with open(args.input, 'r') as file:
        file_content = file.read()

    print(functionstoreplace)
    print(vartionstoreplace)
    for k, v in functionstoreplace.items():
        print(f"{k}: {v}")
        file_content = file_content.replace(k + '(', v + '(')

    for k, v in vartionstoreplace.items():
        print(f"{k}: {v}")
        file_content = file_content.replace(f' {k} = ', f' {v} = ')
        file_content = file_content.replace(f'({k})', f'({v})')
        file_content = file_content.replace(f'[{k}', f'[{v}')
        file_content = file_content.replace(f' {k} ', f' {v} ')
        file_content = file_content.replace(f' {k}.', f' {v}.')
        file_content = file_content.replace(f'({k}.', f'({v}.')
        file_content = file_content.replace(f'{{{k}.', f'{{{v}.')
        file_content = file_content.replace(f'{k}[', f'{v}[')
        file_content = file_content.replace(f'= {k}', f'= {v}')
        file_content = file_content.replace(f'={k}', f'={v}')
        file_content = file_content.replace(f' {k}:', f' {v}:')
        file_content = file_content.replace('{' + k + '}', '{' + v + '}')

    file_content = file_content.replace('\n\n', '\n')
    file_content = file_content.replace('    ', '\t\t\t\t\t\t\t\t')

    with open(args.output, "w", encoding="utf-8") as file:
        file.write(file_content)

if __name__ == "__main__":
    main()
