#!/usr/bin/env python3
import sys
import base64
import re
import argparse as ap
import random
import string
def ebJykYoH():
								sWauKAoW = "op"
def XwbOZmYp(line):
								mnCrcIvu = re.search(r"^def .*\(.*\):", line)
								if mnCrcIvu:
																dOyXzKBR = re.split(r'def |\(', mnCrcIvu.group())
																return dOyXzKBR[1]
								else:
																return None
def nPBmnGOB(line):
								sclIwEUb = re.search(r"\w+ = ", line)
								if sclIwEUb:
																MWDiPABA = re.split(r' = ', sclIwEUb.group())
																return MWDiPABA[0]
								else:
																return None
def nJpqpwOb():
								LirbGlRu = ap.ArgumentParser()
								LirbGlRu.add_argument('-i', '--input', required=True)
								LirbGlRu.add_argument('-o', '--output', required=True)
								LDBpJuQl = LirbGlRu.parse_args()
								print(f"INPUT: {LDBpJuQl.input}, OUTPUT: {LDBpJuQl.output}")
								PuCscCIV = {}
								KlCWCfbW = {}
								with open(LDBpJuQl.input, 'r', encoding="utf-8") as file:
																for line in file:
																								RvwyqAys = XwbOZmYp(line)
																								if RvwyqAys:
																																dKLDFsOo = 8
																																gCUGxVDL = ''.join(
																																								random.choices(
																																																string.ascii_letters, k=dKLDFsOo)).strip()
																																PuCscCIV[RvwyqAys.strip()] = gCUGxVDL
																								Bhuivtkd = nPBmnGOB(line)
																								if Bhuivtkd:
																																dKLDFsOo = 8
																																QohVGdpj = ''.join(
																																								random.choices(
																																																string.ascii_letters, k=dKLDFsOo)).strip()
																																KlCWCfbW[Bhuivtkd.strip()] = QohVGdpj
								with open(LDBpJuQl.input, 'r') as file:
																FnJNTJhp = file.read()
								print(PuCscCIV)
								print(KlCWCfbW)
								for k, v in PuCscCIV.items():
																print(f"{k}: {v}")
																FnJNTJhp = FnJNTJhp.replace(k + '(', v + '(')
								for k, v in KlCWCfbW.items():
																print(f"{k}: {v}")
																FnJNTJhp = FnJNTJhp.replace(f' {k} = ', f' {v} = ')
																FnJNTJhp = FnJNTJhp.replace(f'({k})', f'({v})')
																FnJNTJhp = FnJNTJhp.replace(f'[{k}', f'[{v}')
																FnJNTJhp = FnJNTJhp.replace(f' {k} ', f' {v} ')
																FnJNTJhp = FnJNTJhp.replace(f' {k}.', f' {v}.')
																FnJNTJhp = FnJNTJhp.replace(f'({k}.', f'({v}.')
																FnJNTJhp = FnJNTJhp.replace(f'{{{k}.', f'{{{v}.')
																FnJNTJhp = FnJNTJhp.replace(f'{k}[', f'{v}[')
																FnJNTJhp = FnJNTJhp.replace(f'= {k}', f'= {v}')
																FnJNTJhp = FnJNTJhp.replace(f'={k}', f'={v}')
																FnJNTJhp = FnJNTJhp.replace(f' {k}:', f' {v}:')
																FnJNTJhp = FnJNTJhp.replace('{' + k + '}', '{' + v + '}')
								FnJNTJhp = FnJNTJhp.replace('\n\n', '\n')
								FnJNTJhp = FnJNTJhp.replace('								', '\t\t\t\t\t\t\t\t')
								with open(LDBpJuQl.output, "w", encoding="utf-8") as file:
																file.write(FnJNTJhp)
if __name__ == "__main__":
								nJpqpwOb()
