#!/usr/bin/env python3
"""
pyobf - python obfuscator
Copyright (C) 2026 benja2998
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import sys
import base64
import re
import argparse as ap
import random
import string
def mBxiRSap():
								GDsqcyoR = "op"
def yFVpgohy(line):
								eETNqlZN = re.search(r"^def .*\(.*\):", line)
								if eETNqlZN:
																oNFIfrgr = re.split(r'def |\(', eETNqlZN.group())
																return oNFIfrgr[1]
								else:
																return None
def emKuYpPK(line):
								vbKfZnuo = re.search(r"\w+ = ", line)
								if vbKfZnuo:
																HyWhOAzw = re.split(r' = ', vbKfZnuo.group())
																return HyWhOAzw[0]
								else:
																return None
def xMMYMTkY():
								vOZndUkT = ap.ArgumentParser()
								vOZndUkT.add_argument('-i', '--input', required=True)
								vOZndUkT.add_argument('-o', '--output', required=True)
								RXprmjIM = vOZndUkT.parse_args()
								print(f"INPUT: {RXprmjIM.input}, OUTPUT: {RXprmjIM.output}")
								JeYMsyFE = {}
								yOyCQiaC = {}
								with open(RXprmjIM.input, 'r', encoding="utf-8") as file:
																for line in file:
																								ZoQZlTkc = yFVpgohy(line)
																								if ZoQZlTkc:
																																FtgOSxGQ = 8
																																OYTlfphV = ''.join(
																																								random.choices(
																																																string.ascii_letters, k=FtgOSxGQ)).strip()
																																JeYMsyFE[ZoQZlTkc.strip()] = OYTlfphV
																								wkEnZDaf = emKuYpPK(line)
																								if wkEnZDaf:
																																FtgOSxGQ = 8
																																SCJFYkRV = ''.join(
																																								random.choices(
																																																string.ascii_letters, k=FtgOSxGQ)).strip()
																																yOyCQiaC[wkEnZDaf.strip()] = SCJFYkRV
								with open(RXprmjIM.input, 'r') as file:
																JmzjtXRn = file.read()
								print(JeYMsyFE)
								print(yOyCQiaC)
								for k, v in JeYMsyFE.items():
																print(f"{k}: {v}")
																JmzjtXRn = JmzjtXRn.replace(k + '(', v + '(')
								for k, v in yOyCQiaC.items():
																print(f"{k}: {v}")
																JmzjtXRn = JmzjtXRn.replace(f' {k} = ', f' {v} = ')
																JmzjtXRn = JmzjtXRn.replace(f'({k})', f'({v})')
																JmzjtXRn = JmzjtXRn.replace(f'[{k}', f'[{v}')
																JmzjtXRn = JmzjtXRn.replace(f' {k} ', f' {v} ')
																JmzjtXRn = JmzjtXRn.replace(f' {k}.', f' {v}.')
																JmzjtXRn = JmzjtXRn.replace(f'({k}.', f'({v}.')
																JmzjtXRn = JmzjtXRn.replace(f'{{{k}.', f'{{{v}.')
																JmzjtXRn = JmzjtXRn.replace(f'{k}[', f'{v}[')
																JmzjtXRn = JmzjtXRn.replace(f'= {k}', f'= {v}')
																JmzjtXRn = JmzjtXRn.replace(f'={k}', f'={v}')
																JmzjtXRn = JmzjtXRn.replace(f' {k}:', f' {v}:')
																JmzjtXRn = JmzjtXRn.replace('{' + k + '}', '{' + v + '}')
								JmzjtXRn = JmzjtXRn.replace('\n\n', '\n')
								JmzjtXRn = JmzjtXRn.replace('								', '\t\t\t\t\t\t\t\t')
								with open(RXprmjIM.output, "w", encoding="utf-8") as file:
																file.write(JmzjtXRn)
if __name__ == "__main__":
								xMMYMTkY()
